### ISSUE TITLE
Magister returned error while logging in: 'undefined'

### ISSUE THREAD

**Issue by elisaado** [lieuwex/MahGister#2]
I'm so sorry for this, I don't want to open the first issue, but here I am, opening it :cry: 

When I run `mahgister --help` it just works, the output is like expected.

However, when I do something like `mahgister appointments`
It returns
```node
Magister returned error while logging in: 'undefined'
```

I'm not sure what the problem is, but I got another error when I ran it the first time:
With the command `mahgister`
```node
(node:2309) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
Magister returned error while logging in: 'undefined'
```

Help is appreciated, Thanks! :smile: 

,
Eli

**Comment by lieuwex** [comment]
Hey,

> I'm so sorry for this, I don't want to open the first issue, but here I am, opening it

You shouldn't be sorry, it's actually flattering, since I now know somebody uses my software (or at least tries to).

Apart from the fact that MahGister sucks (I would like to make a CLI to [simplyHomework](https://www.simplyhomework.nl/) one day).

You should just run `mahgister` not `mahgister appointments`, which should be the same actually, mahgister opens a prompt you can use to execute commands.

I have no idea why you this returns an error though, could you take a look in `$HOME/.MahGister/user` and see if everything is correct?

I really hate everything of mahgister, the code, the error handling, the way everything is stored. :P

I will take a look to the warning that is printed on screen though!

**Comment by lieuwex** [comment]
Oh wait, never mind, could you remove `$HOME/.MahGister/user` and rerun mahgister instead?

**Comment by lieuwex** [comment]
Okay I have the same error, you can ignore my request, removing the file seems to fix it temporarily though.

**Comment by lieuwex** [comment]
Sorry for the close, missclick.

**Comment by elisaado** [comment]
I did actually laugh while reading this xD 

It would be nice to have a cli for simplyhomework! 

The last comment did the trick! Thanks for the quick reply and help! 

, 
Eli

**Comment by elisaado** [comment]
OH LOL XD

**Comment by lieuwex** [comment]
Hey @elisaado,

Sorry for the long wait but I fixed the bug by reverting an earlier commit. This means that your password is now stored in plaintext on your harddrive, which can be dangerous, but really shouldn't be that big of a deal.

Remove `$HOME/.MahGister/` and update your MahGister installation, and you should be set!
